# Generated by Django 6.0 on 2026-01-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_person_id_alter_person_ari8moseisagoghs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
