# Generated by Django 6.0 on 2026-01-08 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_uploadlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hmeromhnia_eis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
