# Generated by Django 6.0 on 2026-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_person_hmeromhnia_eis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hmeromhnia_eis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
