# Generated by Django 6.0 on 2026-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_person_hmeromhnia_eis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ari8mosEisagoghs',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
